Events_groupbuy/Events_groupbuy/urls.py
from django.contrib import admin
from django.urls import path, include
from post.views import postNew, showPost,edit_post
from events.views import Started, Joined, show_user, Merch, Movie, Game, Food, Sport, Transit, Other, sortByDate, saveTheMost, lowToHigh, highToLow

urlpatterns = [
	path('', include('main.urls')),
	path('events/', include('events.urls')),
    path('admin/', admin.site.urls),
    path('post/', postNew),
    path('create/', postNew),

    path('events/joined', Joined),
    path('events/started', Started),

    path('events/merch', Merch),
    path('events/movie', Movie),
    path('events/game', Game),
    path('events/food', Food),
    path('events/sport', Sport),
    path('events/transit', Transit),
    path('events/other', Other),

    path('events/sortbydate', sortByDate),
    path('events/savethemost', saveTheMost),
    path('events/lowtohigh', lowToHigh),
    path('events/hightolow', highToLow),
    
    path('editpost/<int:edit_id>', edit_post),

    path('show/<int:u_id>',show_user),
    path('carts/', include('carts.urls')),
    path('orders/', include('orders.urls'))
]

Events_groupbuy/main/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
app_name = "main"

urlpatterns = [
	path('', views.index, name='index'),
	path("register/", views.register, name="register"),
	path('login/', auth_views.LoginView.as_view(template_name='main/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='main/logout.html'), name='logout'),
	path("account/", views.showAcc_info),
	path("edit/", views.edit_view),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Events_groupbuy/post/models.py
from django.db import models

# Create your models here.

Events_groupbuy/post/forms.py
from django import forms
from events.models import Events
from django.core.exceptions import ValidationError
import datetime
import pytz


class event_created(forms.ModelForm):
	event_date = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])
	deadline = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])
	error_css_class = 'valid_error'

	class Meta:
		model = Events
		fields = ['title','location','event_type','price','discount_rate','expected_attendants','image_event','deadline','event_date','description']


	def clean(self):
		# cleaned_data = super().clean()
		super(event_created, self).clean() 
		open_date = self.cleaned_data.get('event_date')
		end_date = self.cleaned_data.get('deadline')
		now = datetime.datetime.now()
		now = pytz.utc.localize(now)
		# current = datetime.datetime.now().strftime('%d/%m/%Y %H:%M')
		if open_date and end_date:
			if open_date == end_date:
				raise forms.ValidationError("Cannot enter the same event date and dealine date")
			if open_date < end_date:
				raise forms.ValidationError("Cannot set the start the event before dealine")
			if (end_date) < now:
				raise forms.ValidationError("Cannot start in the past")

			return self.cleaned_data
	def __init__(self, *args, **kwargs):
		super(event_created, self).__init__(*args, **kwargs)
		self.fields['price'].label = "Price (CAD)" 
		self.fields['discount_rate'].label = "Discount (0% - 100%)" 
		self.fields['deadline'].label = "Dealine To Apply" 

	def clean_price(self,*args,**kwargs):
		p = self.cleaned_data.get('price')
		if p < 0:
			raise forms.ValidationError("Please enter a positive price")
		return p
	def clean_discount_rate(self,*args,**kwargs):
		dis_rate = self.cleaned_data.get('discount_rate')
		if dis_rate < 0 or dis_rate > 100:
			raise forms.ValidationError("Please enter a valid dicount rate")
		# if isinstance(dis_rate,float):
		# 	raise forms.ValidationError("Disocunt cannot be a floating number ")
		return dis_rate
	def clean_expected_attendants(self,*args,**kwargs):
		num = self.cleaned_data.get('expected_attendants')
		if num <= 0:
			raise forms.ValidationError("Attendants cannot be Zero")
		return num			

class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Events
        fields = ['title','location','event_type','discount_rate', 'expected_attendants','image_event','description']

    def clean_image_event(self):
    	t = self.cleaned_data.get('image_event')
    	if t:
    		return t
    	else:
    		raise forms.ValidationError("You cannot clear the image. You must have one image")

Events_groupbuy/post/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from events.models import Events
from .forms import event_created,PostUpdateForm
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib import messages
def showPost(request):

	return render(request, 'post/base.html')




def postNew(request):
	if request.user.is_anonymous:
		return redirect('/login/')
	print(request.user)
	if request.method == 'POST':
		e_form = event_created(request.POST,request.FILES)
		if e_form.is_valid():
			
			u_event = e_form.save()
			u_event.owner = request.user
			discount = float(request.POST.get('discount_rate'))
			discount = 100 - discount
			discount = discount/100
			print(discount)
			# u_event.discount_rate = discount
			u_event.save()

			print("Save event ")
			# messages.success(request, f'Your event has been updated!')
			now = datetime.datetime.now().strftime('%d/%m/%Y %H:%M')
			print(now)
			return redirect('/events/started')
	else:
		e_form = event_created()
	return render(request, 'post/base.html', {
        'e_form': e_form
    })



def edit_post(request,edit_id):
	if request.user.is_anonymous:
		return redirect('/login/')
	if edit_id:
		p = Events.objects.get(pk=edit_id)
		if(p.owner != request.user):
			error = "You cannot edit this post since you are not the owner"
			return render(request, 'post/edit_post.html', {'error': error})
	else:
		p = None
	if request.method == 'POST':
		e_form = PostUpdateForm(request.POST,
                                   request.FILES,
                                   instance=p)
		if e_form.is_valid():
			e_form.save()
			print("Save img")
			messages.success(request, f'Your post got updated')
			return redirect('/events/started')
	else:
		e_form = PostUpdateForm(instance=p)
	return render(request, 'post/edit_post.html', {'e_form': e_form})

Events_groupbuy/post/templates/post/base.html
{% extends 'main/nav.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<head>

  <!-- XDSoft DateTimePicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

</head>

<!-- <div class="container">
	<div class="row">

	    <div class="col-md-8 col-md-offset-2">

    		<h1>Create My Event</h1>

    		<form action="/create/" method="POST" enctype="multipart/form-data">{% csrf_token %}

    		    <div class="form-group">
    		        <label for="title">Title <span class="require">*</span></label>
    		        <input type="text" class="form-control" name="title" required/>
    		    </div>

                <div class="form-group">
                    <label for="location">Location</label>
                     <input type="text" class="form-control" name="location" required/>
                </div>

                <div class="form-group">
                    <label for="event_date">Event Date</label>
                     <input type="datetime-local" class="form-control" name="event_date" required/>
                </div>

                <div class="form-group">
                    <label for="event_type">Event Type</label>
                    <br>
                    <select name="event_type">
                        <option value="MOVIE">Movie</option>
                        <option value="SPORTS">Sports</option>
                        <option value="GAMES">Games</option>
                        <option value="FOOD">Food</option>
                        <option value="TRANSIT">Transit</option>
                        <option value="MERCH">Merch</option>
                        <option value="OTHER">Other</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="price">Price (CAD)</label>
                     <input type="number" step="0.01" class="form-control" name="price" required/>
                </div>

                <div class="form-group">
                    <label for="expected_attendants">Expected Attendants</label>
                     <input type="number" min="1" class="form-control" name="expected_attendants" required/>
                </div>

                <div class="form-group">
                    <label for="deadline">Deadline</label>
                     <input type="datetime-local" class="form-control" name="deadline" required/>
                </div>

    		    <div class="form-group">
    		        <label for="description">Description</label>
    		        <textarea rows="5" class="form-control" name="description" required></textarea>
    		    </div>

    		    <div class="form-group">
    		        <p><span class="require">*</span> - required fields</p>
    		    </div>


                <div class="form-group">
                    <label for="image" >Events Image <span class="require">*</span></label>
                    <input type="file" name="image" accept="image/*" >
                </div>


    		    <div class="form-group" action="/addNew/" method="post">{% csrf_token %}
    		        <button type="submit" class="btn btn-primary">
    		            Create
    		        </button>
    		    </div>

    		</form>
		</div>
 -->
    <br>
    <div class="container">
       <div class="row">
         <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
           <div class="card card-signin my-5">
             <div class="card-body">
               <h5 class="card-title text-center">Create An Event</h5>
               <form method="POST" enctype="multipart/form-data">
                 <div class="form-label-group">
                   {% csrf_token %}
                   {{e_form|crispy}}
                 </div>
                 <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Created</button>
               </form>

             </div>
           </div>
         </div>
       </div>
     </div>

{% endblock %}
{% block javascript %}
  $(function () {
    $("#id_event_date").datetimepicker({
      format: 'd/m/Y H:i',
    });
        $("#id_deadline").datetimepicker({
      format: 'd/m/Y H:i',
    });
  });
{% endblock %}

Events_groupbuy/post/templates/post/edit_post.html
{% extends 'main/nav.html' %}
{% load crispy_forms_tags %}
{%block title %}
<h1 class="display-3">Edit Information</h1>
{%endblock%}
{% block content %}
<!-- {% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">
{{ message }}
</div>
{% endfor %}
{% endif %} -->
{% if error == nil %}
<br>
<div class="container">
   <div class="row">
     <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
       <div class="card card-signin my-5">
         <div class="card-body">
           <h5 class="card-title text-center">Updated Your Information</h5>
           <form method="POST" enctype="multipart/form-data">
             <div class="form-label-group">
               {% csrf_token %}
               {{e_form|crispy}}
             </div>
             <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">UPDATE</button>
           </form>
           <div class="border-top pt-3">
               <small class="text-muted">
                   Don't want to Update? Go back to your Profile page <a class="ml-2"a href="/account">Back</a>
               </small>
           </div>

         </div>
       </div>
     </div>
   </div>
 </div>
 {% endif %}
 {% if error %}
<h3>{{error}}</h3>
{% endif %}
{%endblock%}

Events_groupbuy/post/templates/post/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Events_Groupbuy</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">Events GroupBuy</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/events">Event List
                <span class="sr-only">(current)</span>
              </a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="/post">Start Your Own Event
            <span class="sr-only">(current)</span>
          </a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="/account/{{user.id}}">{{user.username|title}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/logout">Log out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="/login">Log in</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/register">Sign up</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
    {% block content %}
    {% endblock %}
</body>
</html>